sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    access-key-id: LTAI5tJWWggGJyvBRFTM5he2
    access-key-secret: x5ONzvoEh81zSWBigerdX2mmPrzRYV
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: itheima-sky-take-out-bucket